channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=25.0.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.0
name: mlflow-env
